#!/usr/bin/env bash

# Version = ${project.version}

# Parse args
install_opts=()
while [ $# -gt 0 ]
do
  install_opts+=("$1")
  case "$1" in
    -v)
      verbose=true
      ;;
  esac
  shift
done

# Find java executable
JAVA_CMD=$(type -p java)
if [[ ! -n "$JAVA_CMD" ]]; then
  if [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]]; then
    JAVA_CMD="$JAVA_HOME/bin/java"
  else
    >&2 echo "Couldn't find 'java'. Please set JAVA_HOME."
  fi
fi

install_dir=PREFIX

if [[ ! -n "$CLJ_CONFIG" ]]; then
  clojure_dir="$CLJ_CONFIG"
elif [[ ! -n "$XDG_CONFIG_HOME" ]]; then
  clojure_dir="$XDG_CONFIG_HOME/clojure"
else
  clojure_dir="$HOME/.clojure"
fi

if [[ ! -d "$clojure_dir" ]]; then
  if [[ -n $verbose ]]; then echo "Creating $clojure_dir"; fi
  mkdir -p "$clojure_dir"
fi

if [[ -e "$clojure_dir/clj.props" ]]; then
  if [[ -n $verbose ]]; then echo "Backing up $clojure_dir/clj.props"; fi
  cp -f "$clojure_dir/clj.props" "$clojure_dir/clj.props.backup"
fi
if [[ -n $verbose ]]; then echo "Writing: $clojure_dir/clj.props"; fi
cp "$install_dir/clj.props" "$clojure_dir/clj.props"

# Run initial dependency installer
"$JAVA_CMD" -classpath "$install_dir/install-clj-${project.version}.jar" clojure.tools.Install "$clojure_dir" "${install_opts[@]}"
