#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Unquotes the first argument passed
#
# Results are written to global array `args'
#

function unquote() {
    s="$1"
    args=()
    arg=""

    for (( i=0; i<${#s}; i++ )); do
        c="${s:$i:1}"

        if [[ "$c" == $'\n' ]]; then
            if [[ "$arg" != "" ]]; then
                args+=("$arg")
                arg=""
            fi
        elif [[ "$c" == "\\" ]]; then
            i=$((i + 1))
            c="${s:$i:1}"
            arg="${arg}${c}"
        else
            arg="${arg}${c}"
        fi
    done

    if [[ "$arg" != "" ]]; then
        args+=("$arg")
        arg=""
    fi
}

function dump() {
    python -c "import sys, json; sys.stdout.write(json.dumps(sys.argv[1:]))" "$@"
}

function check() {
    actual="$(dump "${args[@]}")"
    if [[ "$actual" != "$expected" ]]; then
        echo "Assertion failed"
        printf "actual:   %s\n" "$actual"
        printf "expected: %s\n" "$expected"
        exit 1
    else
        echo "Ok"
    fi
}

unquote $'foo bar'
expected='["foo bar"]'
check

unquote $'foo\nbar'
expected='["foo", "bar"]'
check

unquote $'-co\n{:aot-cache true}'
expected='["-co", "{:aot-cache true}"]'
check
