name: Check download via setup-clojure

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS to check installation with'
        required: true
        default: 'ubuntu-latest'
      version:
        description: 'Version to check installation with'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}
    steps:
    - name: Set Github identity
      run: |
        git config --global user.name clojure-build
        git config --global user.email "clojure-build@users.noreply.github.com"
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@latest
      with:
        cli: ${{ github.event.inputs.version }}
    - name: Use clojure
      run: clojure --version
