name: Check get latest

on: [workflow_dispatch]
  inputs:
    version:
      description: 'Version to check installation with'
      required: true
      default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set Github identity
      run: |
        git config --global user.name clojure-build
        git config --global user.email "clojure-build@users.noreply.github.com"
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        cli: ${{ github.event.inputs.version }}
    - name: Use clojure
      run: clojure --version
