name: Promote dev to stable

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set Github identity
      run: |
        git config --global user.name clojure-build
        git config --global user.email "clojure-build@users.noreply.github.com"
    - name: Read versions
      run: |
        source script/read_versions.sh
        cp devel.properties stable.properties
        git add stable.properties
        git commit -m "update stable to $DEVEL_VERSION"
        git push
    - name: Publish new stable version
      run: aws s3 cp --only-show-errors "stable.properties" "$S3_BUCKET/install/stable.properties"
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
    - name: Change brew recipe in tap
      run: |
        echo "old $STABLE_VERSION"
        gh workflow run -R clojure/homebrew-tools promote -r master -f old_version="$STABLE_VERSION" -f old_sha="$STABLE_SHA" -f new_version="$DEVEL_VERSION" -f new_sha="$DEVEL_SHA"
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}
