name: Release dev version

on: [workflow_dispatch]

permissions:        # Exchange the OIDC token (JWT) for a cloud access token
  id-token: write   # This is required for requesting the JWT
  contents: write   # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::173728190221:role/github-CLI-upload
        aws-region: us-east-2
    - name: Check out
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set Github identity
      run: |
        git config --global user.name clojure-build
        git config --global user.email "clojure-build@users.noreply.github.com"
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        cli: latest
    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-
    - name: Calculate version
      run: script/update_version
    - name: Package release
      run: clojure -T:build release
    - name: Upload release to site
      run: script/publish.sh
      env:
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
    - name: Tag release
      run: |
        git tag -a `cat VERSION` -m `cat VERSION`
        git push --tags
        git push
    - name: Publish versioned brew recipe to tap
      run: gh workflow run -R clojure/homebrew-tools publish -r master -f version=$(cat VERSION)
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}
