name: Test trigger

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set Github identity
      run: |
        git config --global user.name clojure-build
        git config --global user.email "clojure-build@users.noreply.github.com"
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        cli: latest
    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-
    - name: Publish versioned brew recipe to tap
      run: gh workflow run -R clojure/homebrew-tools publish.yml -r master -f version=$(cat VERSION)
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}
